name: Deploy to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses:  webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Typescript
      run: yarn global add typescript

    - name: Install Dependencies
      run: yarn --network-concurrency 1

    - name: Serverless AWS authentication
      run: yarn run sls config credentials --provider aws --key ${{ secrets.ACCESS_KEY_ID }} --secret ${{ secrets.SECRET_ACCESS_KEY }}

    - name: Copy production env
      run: 'echo -e "${{secrets.ENV}}" > .env'

    - name: Append auxiliary env variables
      run: 'echo -e "${{secrets.MESSCAT_GOOGLE}}" >> .env'

    - name: Database migrations and generate db types
      run: 'npx prisma migrate deploy && npx prisma generate'

    - name: Compile typescript
      run: 'tsc'

    - name: Deploy Lambda functions
      run: yarn run sls deploy