name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  
jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses:  webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Typescript & serverless
      run: |
        npm i -g typescript
        npm i -g serverless

    - name: Install Dependencies
      run: npm i

    - name: Copy production env
      run: echo -e "${{secrets.ENV}}" > .env

    - name: Database migrations and generate db types
      run: npx prisma migrate deploy && npx prisma generate

    - name: Compile typescript
      run: tsc
    
    - name: Update Dining Menu
      run: npm run fetch:dining