name: Update Data
on:
  schedule:
    - cron: "0 23 * * SUN" # At 11:00 PM, only on Sunday
  workflow_dispatch:
  
jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: yarn --network-concurrency=1

    - name: Compile typescript
      run: tsc
    
    - name: Copy production env
      run: 'echo -e "${{secrets.ENV}}" > .env'
    
    - name: Append auxiliary env variables
      run: 'echo -e "${{secrets.MESSCAT_GOOGLE}}" >> .env'

    - name: Update Dining Menu
      run: yarn fetch:dining